### ISSUE TITLE
Something went wrong with warlock simulator tbc

### ISSUE THREAD

**Issue by fantasybye** [Kristoferhh/WarlockSimulatorTBC#116]
![image](https://user-images.githubusercontent.com/7439627/145041055-513f882e-17bc-4e6d-b4ad-4bd7550a956f.png)

**Comment by Kristoferhh** [comment]
Hi @fantasybye, can you try checking if there's an update available for your browser? If that doesn't fix it then try disabling your extensions since they might be interfering with the website. Let me know if that doesn't fix it.

**Comment by dabing1986** [comment]
@Kristoferhh  my friend has the same issue even use incognito tab . I search it looks like jquery is read multiple times wired enough this issue doesn't happen on my website

**Comment by dabing1986** [comment]
not sure if this link can help https://github.com/Mottie/tablesorter/issues/1179

**Comment by Kristoferhh** [comment]
Yeah I'm guessing the issue is that jQuery is being loaded twice. Every time someone messaged me with this error, it was because they had some extension that was using jQuery, so disabling extensions always fixed it. If it also happens to him in Incognito then the extension might be enabled in Incognito. If it happens in a browser that he's never used before with 0 extensions then I'm not sure what the problem is to be honest, but so far it's always worked to disable extensions.

**Comment by dabing1986** [comment]
@Kristoferhh  By saying  extension you were saying that the chrome extension right ?  
I met the same issue in my other computer .below is what I did 
1. I clean the cached data in the simulation website
2. open the incognito tab and re-access the website again and the issue is gone. 
But I think you are right , maybe some chrome extension is consuming jquery . so I will tell my friend disable all the chrome extension if that is what you mean. thnx

**Comment by grpatter** [comment]
For anyone seeing this in the future, LocalCDN causes this issue. Disable it for the sim to load.
FF: https://addons.mozilla.org/en-US/firefox/addon/localcdn-fork-of-decentraleyes/

If there's a Chrome equivalent, it'll likely cause you issues as well. Possibly Decentraleyes as well, since it uses a similar injection pattern.
